app:
  replicaCount: 2
  image:
    tag: "1.0.0"
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 500m
      memory: 1Gi

db:
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 250m
      memory: 512Mi

secret:
  username: staging_user
  password: staging_oc2024
